// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("3.4.6")]
[assembly: AssemblyFileVersionAttribute("0.3.6")]
[assembly: AssemblyInformationalVersionAttribute("0.3.6")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.4.6";
        internal const string InformationalVersion = "0.3.6";
    }
}
