// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("3.4.9")]
[assembly: AssemblyFileVersionAttribute("0.3.9")]
[assembly: AssemblyInformationalVersionAttribute("0.3.9")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.4.9";
        internal const string InformationalVersion = "0.3.9";
    }
}
